name: two_zero_four_eight
description: A new Flutter project.
publish_to: none

version: 1.0.0+357
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  shared_preferences: ^2.0.8

cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.3.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  image_path_android: "assets/icon.png"
  image_path_ios: "assets/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - icon.png
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: StarJedi
      fonts:
        - asset: fonts/starjedi.ttf
        # - asset: fonts/Schyler-Italic.ttf
        #   style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
