name: two_zero_four_eight
description: A new Flutter project.
publish_to: none

version: 1.0.0+357
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_launcher_icons: ^0.9.2
  hive: ^2.0.4
  shared_preferences: ^2.0.8
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.3.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  image_path_android: "assets/icon.png"
  image_path_ios: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - icon.png
  fonts:
    - family: StarJedi
      fonts:
        - asset: fonts/starjedi.ttf
